name: .NET Core

on:
  push:
    branches: 
      - master 
      - "j03INTHECLOUD/make-source-dir"
  pull_request:
    branches: 
      - master 
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src --configuration Release
    - name: XUnit Test
      run: dotnet test ./src/ShoesXUnitTest --verbosity normal
